apiVersion: apps/v1
kind: Deployment
metadata:
  name: pneuma-kubeflow-notebook
  namespace: dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pneuma-kubeflow-notebook
  template:
    metadata:
      labels:
        app: pneuma-kubeflow-notebook
    spec:
      containers:
      - name: pneuma-kubeflow-notebook
        image: public.ecr.aws/j1r0q0g6/notebooks/notebook-servers/jupyter-tensorflow-full:v1.5.0
        ports:
        - containerPort: 8888
        env:
        - name: NB_PREFIX
          value: "./data"
        #securityContext:
        #  runAsUser: 1000
        #  runAsGroup: 1000
        volumeMounts:
        - name: pneuma-kubeflow-pvc
          mountPath: /home/jovyan
      volumes:
      - name: pneuma-kubeflow-pvc
        persistentVolumeClaim:
          claimName: pneuma-kubeflow-notebook-pvc

