apiVersion: v1
kind: Service
metadata:
  name: pneuma-kubeflow-notebook-svc
  namespace: dev
spec:
  ports:
  - nodePort: 32223
    port: 8888
    protocol: TCP
    targetPort: 8888
  selector:
    app: pneuma-kubeflow-notebook
  type: NodePort

