apiVersion: v1
kind: PersistentVolume
metadata:
  name: pneuma-kubeflow-notebook-pv
  namespace: dev
spec:
  capacity:
    storage: 20Gi
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-storage
  hostPath:
    path: ${KUBEFLOW_PNEUMA_NOTEBOOK_DATA_PATH}
    type: Directory
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - kubeflow
  claimRef:
    name: pneuma-kubeflow-notebook-pvc
    namespace: dev
