apiVersion: v1
kind: PersistentVolume
metadata:
  name: myvolume
  namespace: ckad
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
    - ReadWriteMany
  storageClassName: normal
  hostPath:
    path: "/Users/duaneleem/Code/personal/playground/learning/kubernetes/course-ckad/deleteme"
