apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: myvolume
  namespace: ckad
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: normal
  volumeName: myvolume
  resources:
    requests:
      storage: 4Gi
