# https://argoproj.github.io/argo-workflows/examples/#steps
# https://argoproj.github.io/argo-workflows/examples/#output-parameters
# 
# To run this: argo submit -n argo --watch test-dag.yaml

apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: test-dag-write-lines
spec:
  entrypoint: write-lines
  templates:
  - name: write-lines
    dag:
      tasks:
      - name: A
        template: the-worker
        arguments:
          parameters:
          - name: text
            value: "1st line"
      - name: B
        template: the-worker
        arguments:
          parameters:
          - name: text
            value: "{{tasks.A.outputs.parameters.results-param}}\n2nd line"
      - name: C
        template: the-worker
        arguments:
          parameters:
          - name: text
            value: "{{tasks.B.outputs.parameters.results-param}}\n3rd line"
      - name: D
        template: the-worker
        arguments:
          parameters:
          - name: text
            value: "{{tasks.C.outputs.parameters.results-param}}\n4th line"
      - name: output
        dependencies: [A, B, C, D]
        template: the-output
        arguments:
          parameters:
          - name: text
            value: "{{tasks.D.outputs.parameters.results-param}}"
  
  - name: the-worker
    inputs:
      parameters:
      - name: text
    container:
      image: busybox
      command: ["/bin/sh", "-c"]
      args: ["echo '{{inputs.parameters.text}}' > /tmp/results.txt"]
    outputs:
      parameters:
      - name: results-param
        valueFrom:
          path: /tmp/results.txt
  
  - name: the-output
    inputs:
      parameters:
      - name: text
    container:
      image: busybox
      command: ["/bin/sh", "-c"]
      args: ["echo '{{inputs.parameters.text}}'"]