version: '3.3'

services:
  main:
    image: mysql:5.6
    network_mode: bridge 
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - 3306:3306
    restart: always
    container_name: db-mysql57
    environment:
      MYSQL_ROOT_PASSWORD: password

volumes:
  db_data:
