kind: PersistentVolume
apiVersion: v1
metadata:
  name: db-mysql-main-pv-claim
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 20Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/Users/duaneleem/Code/Other/Kubernetes Volumes/db-mysql-main"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: db-mysql-main-pv-claim
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
