# Docs: https://hub.docker.com/_/wordpress

version: '3.1'

services:
  pneuma-wp-dev:
    image: wordpress:6.0.2-php7.4-apache
    container_name: ${PNEUMA_WP_CONTAINER_NAME}
    restart: unless-stopped
    ports:
      - '${PNEUMA_WP_DEV_PORT}:80'
    volumes:
      - './artifacts/wp-content/themes:/var/www/html/wp-content/themes'
      - './artifacts/wp-content/plugins:/var/www/html/wp-content/plugins'
    environment:
      WORDPRESS_DB_HOST: ${PNEUMA_WP_DB_HOST}
      WORDPRESS_DB_USER: ${PNEUMA_WP_DB_USER}
      WORDPRESS_DB_PASSWORD: ${PNEUMA_WP_DB_PASSWORD}
      WORDPRESS_DB_NAME: ${PNEUMA_WP_DB_NAME}
      WORDPRESS_CONFIG_EXTRA: |
        /* Fix site URL. */
        define("WP_HOME", "${PNEUMA_WP_HOME}:${PNEUMA_WP_DEV_PORT}");
        define("WP_SITEURL", "${PNEUMA_WP_HOME}:${PNEUMA_WP_DEV_PORT}");

        /* WordFence to DB */
        /*define('WFWAF_STORAGE_ENGINE', 'mysqli');*/

networks:
  default:
    external: true
    name: 'development'

