# Creates MySQL for Mio
#
# docker compose -f docker-compose.db-redis.yaml down
# docker compose -f docker-compose.db-redis.yaml up -d

#version: '3.7'

services:
  db-redis:
    image: redis:latest
    restart: always
    container_name: db-redis
    ports:
      - "6379:6379"

networks:
  default:
    external: true
    name: ${DOCKER_NETWORK}

