FROM jupyter/datascience-notebook:python-3.9.6

## Install Python Deps for Freestyle38
RUN pip3 install \
  # Data Science
  numpy \
  pandas \
  alphalens \
  tqdm \
  # Machine Learning
  torch torchvision \
  tensorflow \
  ## NLP
  nltk \
  scikit-learn


