# Jupyter Notebook to develop applications such as ML projects.
#
# @author Duane Leem <duane@leemfamily.com>
# @version 20240710
#
# Build command:
# docker compose down && docker compose up -d
#
# Build command if Dockerfile has changed:
# docker compose down && docker compose up -d --build

version: "3.9"
services:
  personal-jupyter:
    build:
      context: ./
      dockerfile: Dockerfile
    volumes:
      # - "${ONEDRIVE_NOTES}:/home/jovyan/notes"
      # - "${UDACITY_AI_TRADING}:/home/jovyan/udacity-ai-trading"
      - "${DIR_LEVELUP}:/home/jovyan/levelup"
      - "${GH_RESEARCH}:/home/jovyan/research"
    restart: always
    environment:
      JUPYTER_ENABLE_LAB: 'yes'
    ports:
      - "10000:8888"



