apiVersion: v1
kind: Service
metadata:
  name: wordpress-test-loadbalancer
  labels:
    type: wordpress
spec:
  ports:
    - protocol: TCP
      port: 8100
      targetPort: 80
  selector:
    app: wordpress-test
    tier: frontend
    type: wordpress
  type: LoadBalancer
---
apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: wordpress-test
  labels:
    app: wordpress-test
    tier: frontend
    type: wordpress
spec:
  selector:
    matchLabels:
      app: wordpress-test
      tier: frontend
      type: wordpress
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: wordpress-test
        tier: frontend
        type: wordpress
    spec:
      containers:
      - name: wordpress-test
        image: wordpress:5.2.2-php7.3-apache
        # command: ["/bin/bash", "-c", "source /var/www/html/wp-content/other/phpunit-test-runner/.env"]
        env:
        # Name of DB k8s service. Typically a load balancer.
        - name: WORDPRESS_DB_HOST
          value: mysql
        # Schema name.
        - name: WORDPRESS_DB_NAME
          value: wordpress-test
        # Password stored from k8s secrets.
        - name: WORDPRESS_DB_PASSWORD
          value: password
        - name: WORDPRESS_DEBUG
          value: "1"
        ports:
        - containerPort: 80
          name: wordpress-test
        volumeMounts:
        - name: wordpress-test-host-wp-content
          mountPath: /var/www/html/wp-content
        # - name: cm-entrypoint
        #   mountPath: /bin/entrypoint.sh
        #   readOnly: true
      volumes:
      # Link host /wp-content folder.
      - name: wordpress-test-host-wp-content
        hostPath:
          path: /Users/duaneleem/Code/Playground/WordPress Test/wp-content
      # - name: cm-entrypoint
      #   configMap:
      #     defaultMode: 0700
      #     name: wordpress-test-cm-entrypoint
